### ISSUE TITLE
Parent field automated?

### ISSUE THREAD

**Issue by mrenigma** [mrenigma/bolt#1]
Currently to make hierarchal content work you have to add the following to `contenttypes.yml`:

```
fields:
    parent:
        label: Page parent
        type: select
        sort: parent
        values: pages/title
hierarchical: true
```

I wonder if it's possible to make the parent field dynamic? Or do you think it's fine as is?
