### ISSUE TITLE
[HOW-TO] Make hierarchical work

### ISSUE THREAD

**Issue by mrenigma** [mrenigma/bolt#2]
To make hierarchical work you have to add the following to `contenttypes.yml`:

```
fields:
    parent:
        label: Page parent
        type: select
        sort: parent
        values: pages/title
hierarchical: true
```

And add/edit the following in the `router.yml` :

```
contentlink:
    path: /{contenttypeslug}/{slug}
    defaults:
        _controller: controller.frontend:record
    requirements:
        contenttypeslug: controller.requirement:anyContentType
        slug: '[a-z0-9-_\/]+'
```
