### ISSUE TITLE
Backend styling of children items

### ISSUE THREAD

**Issue by mrenigma** [mrenigma/bolt#3]
So looks like the backend listing has changed in the newest version (I have no idea what the main and meta groups mean either!). This needs looking at and styling...

![image](https://user-images.githubusercontent.com/1901969/28998028-c4370dde-7a19-11e7-98ea-c4bdf35c6d27.png)

**Comment by mrenigma** [comment]
@graham73may So looks like I forgot to add styling from soapbox-mods.scss. No JS needs to be copied from there, I just checked.

However I'm a bit stumped as to how to merge into [buic/_listing.scss](https://github.com/mrenigma/bolt/blob/3.3/app/src/sass/buic/_listing.scss):

```scss
/* Hierarchical Contenttypes SBTODO: Move out of this extension
================================================== */
$border-grey : #E8E8E8;

div.buic-listing table.listing tbody.striping_odd tr:nth-of-type(odd), div.buic-listing table.listing tbody.striping_odd tr {
  background : inherit;
}
div.buic-listing table.listing tbody.striping_odd tr.odd {
  background : #F2F4F3;

  table.listing-sub-items tbody tr {
    background : inherit;
  }
}
.listing-sub-items-row .listing-sub-items-container {
  border  : 0;
  padding : 0;
}
.listing-sub-items {
  background-color : inherit;
  width            : 100%;

  td {
    background-color : inherit;
  }
}
.listing-sub-items-row {
  td {
    background-color : inherit;
    border           : inherit;

    &.check {
      width : 30px;
    }

    &.id {
      width : 49px;
    }

    &.username {
      width : 102px;
    }

    &.actions {
      width : 102px;
    }
  }

  &--depth-1 {
    border-bottom : 1px solid $border-grey;
  }

  & & {
    border-top       : 1px solid $border-grey;
    background-color : inherit !important;
  }

  .listing-sub-items-row tr:last-of-type {
    border-bottom : 0;
  }
}
```

Is there a better way we could do this now we have full access to the codebase? I guess this ties with [_sub/_sub-items.twig](https://github.com/mrenigma/bolt/blob/3.3/app/view/twig/_sub/_sub-items.twig) and [_base/_listing.twig](https://github.com/mrenigma/bolt/blob/3.3/app/view/twig/_base/_listing.twig#L135)?
